// <auto-generated />
namespace MediaOrganiser1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials));
        
        string IMigrationMetadata.Id
        {
            get { return "202108250916163_initials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
